### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by s0r00t** [s0r00t/IRCMachine#1]
- [ ] Write docs
- [ ] Write GH command
- [x] ~~Add more fields~~ (unused)
- [x] ~~Add more arguments~~ (unused)
- [x] ~~Add commands~~ (8c71b28e3660b32edc03fec1b5ef05ac9af76dcd)
- [x] ~~Check for bans~~ (9e7f4c258de1a37f011f6e70452e8b2781c6564d)
- [x] ~~Fix unicode error~~ (somehow fixed)
- [x] ~~Make quiet mode work~~ (32cf64b0429da84c680a6cc5ec08613cfbc19f98)
- [x] ~~Log system~~ (32cf64b0429da84c680a6cc5ec08613cfbc19f98)
- [ ] Add shell to CLI interface
- [ ] Check the code, rewrite if needed
- [ ] Take care of the TODOs in the code
